[
### SNTP settings ##############################################################
  ["sntp.enable", false],
################################################################################

### WIFI settings ##############################################################
  ["wifi.ap.enable", false],
  ["wifi.sta.enable", false],
  ["wifi.sta.ssid", "TP-LINK-Landgraf"],
  ["wifi.sta.pass", "07031987"],
################################################################################

### MQTT settings ##############################################################
  ["device.id", "esp0"],
  ["device.password", ""],
# ["mqtt.server", "broker.mqttdashboard.com:1883"],
  ["mqtt.server", "192.168.0.100:1883"],
  ["mqtt.pub", "s", "from/esp0", {title: "Publish topic"}],
  ["mqtt.sub", "s", "to/esp0",   {title: "Subscribe topic"}],
  ["mqtt.ack", "b", false,       {title: "Acknowledge on mqtt request"}],
################################################################################
]
