[
### WIFI settings ##############################################################
  ["wifi.ap.enable", false],
  ["wifi.sta.enable", true],
  ["wifi.sta.ssid", "TP-LINK-Landgraf"],
  ["wifi.sta.pass", "07031987"],
################################################################################

### MQTT settings ##############################################################
  ["device.id", "landgraf"],
  ["device.password", ""],
  ["mqtt.server", "192.168.0.101:1883"],
  ["mqtt.pub", "s", "fromIoT/esp_id0", {title: "Publish topic"}],
  ["mqtt.sub", "s", "toIoT/esp_id0", {title: "Subscribe topic"}],
  ["mqtt.ack", "b", false, {"title": "Acknowledge on mqtt request"}],
################################################################################

### Pin definitions for NodeMCU ################################################
#           D0-->16
#           D1-->5
#           D2-->4
#           D3-->0
#           D4-->2
#           D5-->14
#           D6-->12
#           D7-->13
#           D8-->15
#           D9-->3
#           D10-->1
#           LED_PIN-->D4
################################################################################

### Settings section ###########################################################
  ["settings", "o", {"title": "Custom settings"}],
  ["settings.num_nodes", "i", 2, {"title": "Number of lights or switches"}],
### Light settings #############################################################
  ["settings.light", "o", {"title": "Light settings"}],
  ["settings.light.pin_0", "i", 14, {"title": "Pin for light 0"}],
  ["settings.light.pin_1", "i", 12, {"title": "Pin for light 1"}],
### Switch settings ############################################################
  ["settings.sw", "o", {"title": "Switch settings"}],
  ["settings.sw.pin_0", "i", 4, {"title": "Pin for switch 0"}],
  ["settings.sw.pin_1", "i", 0, {"title": "Pin for switch 1"}],
################################################################################
]
