[
### WIFI settings ##############################################################
  ["wifi.ap.enable", false],
  ["wifi.sta.enable", true],
  ["wifi.sta.ssid", "TP-LINK-Landgraf"],
  ["wifi.sta.pass", "07031987"],
################################################################################

### MQTT settings ##############################################################
  ["device.id", "landgraf"],
  ["device.password", ""],
  ["mqtt.server", "192.168.0.100:1883"],
  ["mqtt.pub", "s", "fromIoT/esp0", {title: "Publish topic"}],
  ["mqtt.sub", "s", "toIoT/esp0", {title: "Subscribe topic"}],
  ["mqtt.ack", "b", false, {"title": "Acknowledge on mqtt request"}],
################################################################################

### Pin definitions for NodeMCU ################################################
#           D0-->16
#           D1-->5
#           D2-->4
#           D3-->0
#           D4-->2
#           D5-->14
#           D6-->12
#           D7-->13
#           D8-->15
#           D9-->3
#           D10-->1
#           LED_PIN-->D4
################################################################################

### Settings section ###########################################################
  ["settings", "o", {hide: true}],
  ["settings.num_nodes", "i", 2, {"title": "Number of nodes"}],
### Light settings #############################################################
  ["settings.light", "o", {hide: true}],
  ["settings.light.pin0", "i", 14, {"title": "Light 0 pin"}],
  ["settings.light.pin1", "i", 12, {"title": "Light 1 pin"}],
### Switch settings ############################################################
  ["settings.sw", "o", {hide: true}],
  ["settings.sw.pin0", "i", 4, {"title": "Switch 0 pin"}],
  ["settings.sw.pin1", "i", 0, {"title": "Switch 1 pin"}],
################################################################################
]
